# ─────────────────────────────────────────────────────────────────────────────
# GATEWAY SERVICE CONFIG
# ─────────────────────────────────────────────────────────────────────────────

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/hero-ecommerce/protocol/openid-connect/certs

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
