package com.hero.bikestore.dto.payment;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Response received from payment-service after payment initiation.
 *
 * Contains the checkout URL that order-service returns to the frontend.
 * The frontend redirects the customer to this URL to complete payment.
 *
 * Dev:  paymentUrl = http://localhost:8086/mock/checkout/{uuid}
 * Prod: paymentUrl = Razorpay hosted checkout URL
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PaymentInitiationResult {

    // The gateway's own ID for this payment session
    // Dev:  UUID generated by MockPaymentProcessor
    // Prod: Razorpay orderId
    private String paymentId;

    // The URL to redirect the customer to for payment
    // Returned to frontend in the order placement response
    private String paymentUrl;
}
