# Bootstrap config — only what's needed BEFORE connecting to config server
spring:
  application:
    name: user-service                               # tells config server which file to serve
  config:
    import: "configserver:http://config-server:8888" # where to fetch the rest of config

server:
  port: 8083

