package com.hero.bikestore.controller;

import com.hero.bikestore.dto.request.PlaceOrderRequest;
import com.hero.bikestore.dto.response.OrderResponse;
import com.hero.bikestore.service.OrderService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/v1/orders")
@RequiredArgsConstructor
public class OrderController {

    private final OrderService orderService;

    /**
     * POST /api/v1/orders
     *
     * Places a new order for the authenticated customer.
     * userId is extracted from the JWT — never passed in the request body.
     *
     * Idempotency-Key header (optional):
     *   A UUID generated by the caller once per checkout intent.
     *   If a request arrives with the same key as an existing order,
     *   the existing order is returned instead of creating a duplicate.
     *   This handles network retries and double-click safely.
     *   Direct Postman calls without the header still work normally.
     *
     * Returns 201 Created (both on first call and on duplicate key hit).
     */
    @PostMapping
    @PreAuthorize("hasRole('CUSTOMER')")
    public ResponseEntity<OrderResponse> placeOrder(
            @Valid @RequestBody PlaceOrderRequest request,
            @RequestHeader(value = "Idempotency-Key", required = false) String idempotencyKey,
            @AuthenticationPrincipal Jwt jwt) {

        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(orderService.placeOrder(request, idempotencyKey, jwt));
    }

    /**
     * GET /api/v1/orders
     *
     * Returns all orders placed by the authenticated customer, newest first.
     * Each customer only sees their own orders.
     *
     * Returns 200 OK with a list (empty list if no orders yet).
     */
    @GetMapping
    @PreAuthorize("hasRole('CUSTOMER')")
    public ResponseEntity<List<OrderResponse>> getMyOrders(
            @AuthenticationPrincipal Jwt jwt) {

        return ResponseEntity.ok(orderService.getMyOrders(jwt));
    }

    /**
     * GET /api/v1/orders/{id}
     *
     * Returns a single order by its database ID.
     * A customer can only fetch their own orders — 403 if the order belongs to someone else.
     *
     * Returns 200 OK, 404 if not found, 403 if not owner.
     */
    @GetMapping("/{id}")
    @PreAuthorize("hasRole('CUSTOMER')")
    public ResponseEntity<OrderResponse> getOrderById(
            @PathVariable Long id,
            @AuthenticationPrincipal Jwt jwt) {

        return ResponseEntity.ok(orderService.getOrderById(id, jwt));
    }

    /**
     * DELETE /api/v1/orders/{id}
     *
     * Cancels a PENDING order placed by the authenticated customer.
     * Stock is automatically restored in inventory-service.
     *
     * Returns 204 No Content on success.
     * Returns 400 if order is not in PENDING status.
     * Returns 403 if the order belongs to someone else.
     * Returns 404 if the order does not exist.
     */
    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('CUSTOMER')")
    public ResponseEntity<Void> cancelMyOrder(
            @PathVariable Long id,
            @AuthenticationPrincipal Jwt jwt) {

        orderService.cancelMyOrder(id, jwt);
        return ResponseEntity.noContent().build();
    }
}
