package com.hero.bikestore.entity;

import com.hero.bikestore.enums.PaymentStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents a single payment attempt for an order.
 *
 * One order can have at most one payment record.
 * orderId is unique — prevents duplicate payments for the same order.
 *
 * Lifecycle:
 *   INITIATED → payment created when order-service sends the command
 *   SUCCESS   → updated when Razorpay/mock webhook confirms capture
 *   FAILED    → updated when Razorpay/mock webhook reports decline
 */
@Entity
@Table(name = "payments")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The order this payment belongs to — must be unique (one payment per order)
    @Column(name = "order_id", nullable = false, unique = true)
    private String orderId;

    // Human-readable reference — stored for receipts and support
    @Column(name = "order_number", nullable = false, length = 30)
    private String orderNumber;

    // Amount to be charged — in INR (or base currency)
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;

    // Customer email — used for receipts
    @Column(name = "user_email")
    private String userEmail;

    // Customer name — used for receipts
    @Column(name = "user_name")
    private String userName;

    // Current state: INITIATED → SUCCESS or FAILED
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private PaymentStatus status;

    // Razorpay/mock transaction ID — populated on SUCCESS
    @Column(name = "transaction_id")
    private String transactionId;

    // Decline reason — populated on FAILED
    // e.g. "Insufficient funds", "Card expired", "Payment timeout"
    @Column(name = "failure_reason")
    private String failureReason;

    // The checkout URL returned to the frontend so customer can pay
    // Razorpay: https://rzp.io/l/abc123
    // Mock:     http://localhost:8086/mock/checkout/{gatewayPaymentId}
    @Column(name = "payment_url")
    private String paymentUrl;

    // The ID the payment gateway uses to identify this payment session.
    // Mock:     UUID generated by MockPaymentProcessor
    // Razorpay: Razorpay orderId e.g. "order_xyz789"
    //
    // WHY THIS FIELD EXISTS:
    // When the mock checkout button is clicked (or Razorpay webhook fires),
    // the only identifier available is this gateway ID.
    // We need it to look up the correct Payment record and update its status.
    @Column(name = "gateway_payment_id", unique = true)
    private String gatewayPaymentId;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
