server:
  port: 8081

spring:
  application:
    name: bike-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#  datasource:
#    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
